// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculateAJ_Rcpp
Rcpp::List calculateAJ_Rcpp(Rcpp::NumericVector t, Rcpp::IntegerVector epsilon, Rcpp::Nullable<Rcpp::NumericVector> w, Rcpp::Nullable<Rcpp::IntegerVector> strata, std::string n_risk_type, std::string error, std::string conf_type, double conf_int, bool return_if, double prob_bound);
RcppExport SEXP _cifmodeling_calculateAJ_Rcpp(SEXP tSEXP, SEXP epsilonSEXP, SEXP wSEXP, SEXP strataSEXP, SEXP n_risk_typeSEXP, SEXP errorSEXP, SEXP conf_typeSEXP, SEXP conf_intSEXP, SEXP return_ifSEXP, SEXP prob_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type n_risk_type(n_risk_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type error(errorSEXP);
    Rcpp::traits::input_parameter< std::string >::type conf_type(conf_typeSEXP);
    Rcpp::traits::input_parameter< double >::type conf_int(conf_intSEXP);
    Rcpp::traits::input_parameter< bool >::type return_if(return_ifSEXP);
    Rcpp::traits::input_parameter< double >::type prob_bound(prob_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateAJ_Rcpp(t, epsilon, w, strata, n_risk_type, error, conf_type, conf_int, return_if, prob_bound));
    return rcpp_result_gen;
END_RCPP
}
// calculateKM
Rcpp::List calculateKM(Rcpp::NumericVector t, Rcpp::IntegerVector d, Rcpp::NumericVector w, Rcpp::IntegerVector strata, std::string error);
RcppExport SEXP _cifmodeling_calculateKM(SEXP tSEXP, SEXP dSEXP, SEXP wSEXP, SEXP strataSEXP, SEXP errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< std::string >::type error(errorSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateKM(t, d, w, strata, error));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cifmodeling_calculateAJ_Rcpp", (DL_FUNC) &_cifmodeling_calculateAJ_Rcpp, 10},
    {"_cifmodeling_calculateKM", (DL_FUNC) &_cifmodeling_calculateKM, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_cifmodeling(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
