name: R-CMD-check
on:
  push: { branches: [ "**" ] }
  pull_request: { branches: [ "**" ] }
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          extra-packages: any::rcmdcheck, any::survival
          needs: check

      - name: Check
        run: |
          R -q -e 'roxygen2::roxygenise()'
          R -q -e 'devtools::test()'
          R -q -e 'rcmdcheck::rcmdcheck(args="--as-cran", error_on="warning")'
