name: R-CMD-check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          extra-packages: any::rcmdcheck
          needs: check
      - name: Check
        shell: Rscript {0}
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning")
