name: R-CMD-check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      roxygenise:
        description: "Run roxygen2::roxygenise() before checking?"
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          extra-packages: any::rcmdcheck, any::survival
          needs: check

      - name: (optional) roxygenise
        if: ${{ inputs.roxygenise == true }}
        shell: Rscript {0}
        run: |
          roxygen2::roxygenise()

      - name: Check
        shell: Rscript {0}
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual","--as-cran"),
                               error_on = "warning")
